//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCID_Monitor.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GermanResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GermanResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCID_Monitor.Properties.GermanResources", typeof(GermanResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hinzufügen ähnelt.
        /// </summary>
        internal static string button_Add {
            get {
                return ResourceManager.GetString("button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ändern ähnelt.
        /// </summary>
        internal static string button_Change {
            get {
                return ResourceManager.GetString("button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die clear ähnelt.
        /// </summary>
        internal static string button_Clear {
            get {
                return ResourceManager.GetString("button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die entfernen ähnelt.
        /// </summary>
        internal static string button_Delete {
            get {
                return ResourceManager.GetString("button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die speichern &amp;&amp; neustarten ähnelt.
        /// </summary>
        internal static string button_SaveRestart {
            get {
                return ResourceManager.GetString("button_SaveRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die erzeuge Logdateien ähnelt.
        /// </summary>
        internal static string checkBox_CreateLogfiles {
            get {
                return ResourceManager.GetString("checkBox_CreateLogfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anrufzeit ähnelt.
        /// </summary>
        internal static string headertext_Calltime {
            get {
                return ResourceManager.GetString("headertext_Calltime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        /// </summary>
        internal static string headertext_Duration {
            get {
                return ResourceManager.GetString("headertext_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ltg. ähnelt.
        /// </summary>
        internal static string headertext_Line {
            get {
                return ResourceManager.GetString("headertext_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Rufnummer ähnelt.
        /// </summary>
        internal static string headertext_LocalName {
            get {
                return ResourceManager.GetString("headertext_LocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Rufnummer ähnelt.
        /// </summary>
        internal static string headertext_LocalNR {
            get {
                return ResourceManager.GetString("headertext_LocalNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string headertext_Name {
            get {
                return ResourceManager.GetString("headertext_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nummer ähnelt.
        /// </summary>
        internal static string headertext_Number {
            get {
                return ResourceManager.GetString("headertext_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefoniegerät ähnelt.
        /// </summary>
        internal static string headertext_PhoneID {
            get {
                return ResourceManager.GetString("headertext_PhoneID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon Name ähnelt.
        /// </summary>
        internal static string headertext_PhoneName {
            get {
                return ResourceManager.GetString("headertext_PhoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfernter Name ähnelt.
        /// </summary>
        internal static string headertext_RemoteName {
            get {
                return ResourceManager.GetString("headertext_RemoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name / Rufnummer ähnelt.
        /// </summary>
        internal static string headertext_RemoteNR {
            get {
                return ResourceManager.GetString("headertext_RemoteNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hostname ähnelt.
        /// </summary>
        internal static string label_Hostname {
            get {
                return ResourceManager.GetString("label_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string label_Language {
            get {
                return ResourceManager.GetString("label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string label_Name {
            get {
                return ResourceManager.GetString("label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nummer ähnelt.
        /// </summary>
        internal static string label_Number {
            get {
                return ResourceManager.GetString("label_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        internal static string label_Port {
            get {
                return ResourceManager.GetString("label_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verzögerung ähnelt.
        /// </summary>
        internal static string label_ToolTipDelay {
            get {
                return ResourceManager.GetString("label_ToolTipDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        internal static string language_Default {
            get {
                return ResourceManager.GetString("language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die englisch ähnelt.
        /// </summary>
        internal static string language_english {
            get {
                return ResourceManager.GetString("language_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deutsch ähnelt.
        /// </summary>
        internal static string language_german {
            get {
                return ResourceManager.GetString("language_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        internal static string menuExitItem {
            get {
                return ResourceManager.GetString("menuExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log ähnelt.
        /// </summary>
        internal static string menuLogItem {
            get {
                return ResourceManager.GetString("menuLogItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string menuSettingsItem {
            get {
                return ResourceManager.GetString("menuSettingsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
        /// </summary>
        internal static string tabpage_General {
            get {
                return ResourceManager.GetString("tabpage_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefonbuch ähnelt.
        /// </summary>
        internal static string tabpage_Phonebook {
            get {
                return ResourceManager.GetString("tabpage_Phonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefone ähnelt.
        /// </summary>
        internal static string tabpage_Phones {
            get {
                return ResourceManager.GetString("tabpage_Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die aktiv ähnelt.
        /// </summary>
        internal static string text_active {
            get {
                return ResourceManager.GetString("text_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nummer bereits unter einem anderen Eintrag im Telefonbuch ähnelt.
        /// </summary>
        internal static string text_already_at_other_entry_in_phonebook {
            get {
                return ResourceManager.GetString("text_already_at_other_entry_in_phonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nummer bereits im Telefonbuch ähnelt.
        /// </summary>
        internal static string text_already_in_phonebook {
            get {
                return ResourceManager.GetString("text_already_in_phonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die verbunden ähnelt.
        /// </summary>
        internal static string text_connected {
            get {
                return ResourceManager.GetString("text_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei nicht gefunden! ähnelt.
        /// </summary>
        internal static string text_file_not_found {
            get {
                return ResourceManager.GetString("text_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei &quot;{0}&quot; konnte nicht gelesen werden!\n\nVerwende Voreinstellungen. ähnelt.
        /// </summary>
        internal static string text_file_not_readable {
            get {
                return ResourceManager.GetString("text_file_not_readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die warte ähnelt.
        /// </summary>
        internal static string text_waiting {
            get {
                return ResourceManager.GetString("text_waiting", resourceCulture);
            }
        }
    }
}
